### ISSUE TITLE
設定ファイル

### ISSUE THREAD

**Issue by bromne** [opap-jp/material-explorer#7]
@butameron 
JIRA での通り、このシステムでは、**取得リポジトリ**と**タグ宣言**を指定したうえで、リポジトリのインデックスなどを行ないます。
https://github.com/opap-jp/material-explorer/wiki/Formats に、取得リポジトリ設定ファイルとタグ宣言設定ファイルのフォーマットの案があります。
さて、この設定ファイルについて意見をうかがいたいと思います。

1. いまところ、とりあえず取得リポジトリとタグ宣言を別のファイルということにしてしまいましたが、個人的には一つのファイルをまとめて行なうというのでもよいと思っています。（まとまっているほうが編集が楽かな……と。）  
どちらがよさそうでしょうか？
1. これらの（この）設定ファイルの取得方法はどのようなものがよいか。
    1. ローカルのファイル
    1. ネットワーク上のリソース（URLで指定。）
    1. ローカル，ネットワーク上どちらでも可

**Comment by butameron** [comment]
最終的な記述分量が多くなるのであれば、ファイルが分かれたままの方が良いと思います。あまりにも内容が多いと、編集したいところにたどり着く前にやる気をなくしてしまいそうです。

柔軟にしようとするなら設定ファイルにインクルードの仕様を追加することですが、ただでさえyamlの実装が面倒なのに、そこまではする必要はそれほどないと思います。

将来的にWebUIから編集できるようにする前提であれば、1つのファイルにまとめてしまって、ビルド時にDBに投入するようにしても良いと思います。（再ビルドの時はDBから設定を削除した上で、再投入する形？）

設定ファイルの取得は、セキュリティ的な観点ではローカルのファイルかなと思います。リモートファイルのほうが運用面では良さそうではあるのですが、もしかするとパスワードやAPIキーのような公開できない情報も記述しなければならない場合がありそうだからです。

**Comment by bromne** [comment]
> 最終的な記述分量が多くなるのであれば、ファイルが分かれたままの方が良いと思います。あまりにも内容が多いと、編集したいところにたどり着く前にやる気をなくしてしまいそうです。

ファイルがまとまっていたとして、おそらく、『こうしす！』6話まで作ったとしてファイルが100行行くか行かないかというぐらいかと思います。  
とりあえず分かれたままとします。


> （再ビルドの時はDBから設定を削除した上で、再投入する形？）

設定をそのままデータベースに保存する必要はないかも知れません。（その場合、再投入というような話にはならない。）  
データ更新のタイミングはまだあまり考えてないのですが、少なくともシステムの起動（再ビルドの場合を含む）時にはデータ更新が行なわれると思います。  

> もしかするとパスワードやAPIキーのような公開できない情報も記述しなければならない場合がありそう

取得リポジトリとタグ宣言の設定より上位の設定ファイルとして、[REST アプリケーションそのものの設定](https://github.com/opap-jp/material-explorer/blob/develop/rest/config.develop.yaml)（フレームワークでサポートされている。）があります。（取得リポジトリとタグ宣言の設定の場所もこの設定ファイルに書くことにしました。）

データベースのパスワードなどグローバルな秘密情報はここに書けばよいと思いますが、単一のリポジトリにも秘密情報を書く可能性があるのであれば、ローカルですね。

**Comment by bromne** [comment]
ちなみに、設定ファイルを変更して文法エラーその他の致命的なエラーが生じたときは、「取得リポジトリが0個」，「タグ宣言が0個」のような扱いになります。（システムの動作を止めるわけにはいかないため。）
